name: CI

on:
  push:
    branches:
      - main
      - master
      - road-to-v1
  pull_request: {}

concurrency:
  group: ci-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Tests"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: <%= yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= yarn ? 'yarn install --frozen-lockfile' : 'npm ci' %>
      - name: Lint
        run: <%= yarn ? 'yarn' : 'npm run' %> lint
      - name: Run Tests
        run: <%= yarn ? 'yarn' : 'npm run' %> test
  floating:
    name: "Floating Dependencies"
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: <%= yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= yarn ? 'yarn install --no-lockfile' : 'npm install --no-shrinkwrap' %>
      - name: Run Tests
        run: <%= yarn ? 'yarn' : 'npm run' %> test

  try-scenarios:
    name: ${{ matrix.try-scenario }}
    runs-on: ubuntu-latest
    needs: "test"
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        try-scenario:
          - ember-lts-2.18
          - ember-lts-3.12
          - ember-lts-3.16
          - ember-lts-3.28
          - ember-release
          - ember-beta
          - ember-canary
          - ember-classic

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 12.x
          cache: <%= yarn ? 'yarn' : 'npm' %>
      - name: Install Dependencies
        run: <%= yarn ? 'yarn install --frozen-lockfile' : 'npm ci' %>
      - name: Run Tests
        run: ./node_modules/.bin/ember try:one ${{ matrix.try-scenario }}
